using MMTP_Parser.Entity.Custom;
using MMTP_Parser.Entity.MMTP.DIFF.BusinessData;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MMTP_Parser.Tools;
using System.Numerics;

namespace MMTP_Parser.Entity.MMTP.DIFF
{
    public class Header
    {
        public ObservableCollection<Field> _ObsFields { get; set; }
        public BusinessDataHeader _BusinessDataHeader { get; set; }
        private decimal _BusinessDataLength = 0;
        public bool _IsFirstSubFiled = false;
        //***************************************************************************************
        public void FillFirstSub(Byte[] vArrFirstSub)
        {
            decimal xStartOfText = vArrFirstSub.SubArray(0, 1).ToNumerical();
            _ObsFields = new ObservableCollection<Field>();
            Field xField;

            if (xStartOfText == 2)
            {
                _BusinessDataLength = Convert.ToDecimal(Encoding.Default.GetString(vArrFirstSub.SubArray(19, 4)));

                xField = new Field("STX", FieldType.Numerical, 1, 0, "Start of text", "02");
                _ObsFields.Add(xField);

                xField = new Field("Length_Of_Primitive", FieldType.Numerical, 4, 1, "Length of Primitive", "96+m");
                _ObsFields.Add(xField);

                xField = new Field("Primitive_Identifier", FieldType.Numerical, 2, 5, "Primitive Identifier", "23");
                _ObsFields.Add(xField);

                xField = new Field("Sequence_Number", FieldType.Numerical, 8, 7, "Message sequence number generated by sender", "");
                _ObsFields.Add(xField);

                xField = new Field("Admin_Data_Length", FieldType.Numerical, 4, 15, "Length of admin data field", "72");
                _ObsFields.Add(xField);

                xField = new Field("Business_Data_Length", FieldType.Numerical, 4, 19, "Length of business data", "m");
                _ObsFields.Add(xField);

                xField = new Field("Admin_Data_Type", FieldType.Alphanumerical, 2, 23, "Data Format", "");
                _ObsFields.Add(xField);

                xField = new Field("Message_ID", FieldType.Alphanumerical, 24, 25, "Unique message ID assigned by sender", "");
                _ObsFields.Add(xField);

                xField = new Field("Send_Timestamp", FieldType.Numerical, 12, 49, "Date and time of transmission", "");
                _ObsFields.Add(xField);

                xField = new Field("Delivery_Timestamp", FieldType.Numerical, 12, 61, "Date and time of delivery", "");
                _ObsFields.Add(xField);

                xField = new Field("Delivery_Timeout", FieldType.Numerical, 6, 73, "Delivery timeout", "HHMMSS");
                _ObsFields.Add(xField);

                xField = new Field("Route_Data", FieldType.Alphanumerical, 11, 79, "Additional routing data", "");
                _ObsFields.Add(xField);

                xField = new Field("Filler_1", FieldType.Alphanumerical, 5, 90, "", "");
                _ObsFields.Add(xField);

                _ObsFields.FillArrByteInObsField(vArrFirstSub);
                _IsFirstSubFiled = true;
            }
        }
        //***************************************************************************************
        public void FillSecondSub(Byte[] vArrSecondSub)
        {
            Field xField;
            xField = new Field("ETX", FieldType.Numerical, 1, _BusinessDataLength.Nvl(0), "End of text", "03");
            xField._Numerical = vArrSecondSub.SubArray(xField._Position, xField._Length).ToNumerical();
            _ObsFields.Add(xField);
            _BusinessDataHeader = new BusinessDataHeader(vArrSecondSub.SubArray(0, _BusinessDataLength.Nvl(0)));
        }
    }
}
